#[derive(Debug, Clone)]
pub struct Weights {
    pub base_key: f64,
    pub rest_distance: f64,
    pub dynamic_distance: f64,
    pub palm_distance: f64,
    pub palm_tension: f64,
    pub row_top: f64,
    pub row_home: f64,
    pub row_bottom: f64,
    pub row_number: f64,
    pub pinky_start: f64,
    pub shift: f64,
    pub left_shift_right_reach: f64,
    pub beat_interval: f64,
    pub finger_recovery: f64,
    pub movement_recovery: f64,
    pub movement_time_factor: f64,
    pub row_change_time: f64,
    pub stretch_time: f64,
    pub timing_wait: f64,
    pub same_key_motion: f64,
    pub same_finger_motion: f64,
    pub recent_same_finger: f64,
    pub two_finger_bounce: f64,
    pub abba_bounce: f64,
    pub same_hand: f64,
    pub hand_switch_onehand: f64,
    pub hand_switch_neutral: f64,
    pub hand_switch_alternation: f64,
    pub prefer_hand_penalty: f64,
    pub adjacent_roll_reward: f64,
    pub forward_roll_reward: f64,
    pub reverse_roll_penalty: f64,
    pub compact_cluster_reward: f64,
    pub smooth_trigram_reward: f64,
    pub reverse_trigram_penalty: f64,
    pub full_sweep_reward: f64,
    pub reverse_full_sweep_penalty: f64,
    /// FEW(A/Q)-like reverse upper clusters are a user-observed variant of FDSA:
    /// middle -> E drags ring near W, then pinky lands near Q or drops to A.
    pub upper_reverse_coupled_roll_reward: f64,
    pub upper_reverse_axis_relief: f64,
    pub upper_reverse_split_sweep_reward: f64,
    pub home_return_wait_relief: f64,
    /// Directional setup before a four-finger sweep. User testing showed that
    /// DF+ASDF is more natural than FD+ASDF: the latter reverses direction
    /// immediately before entering a left-to-right motor program.
    pub pre_sweep_direction_change_penalty: f64,
    pub pre_sweep_direction_match_reward: f64,
    pub home_sweep_reward: f64,
    pub non_home_sweep_reward_factor: f64,
    pub mixed_row_sweep_penalty: f64,
    pub asymmetric_row_actuation: f64,
    pub motor_program_repeat_reward: f64,
    pub mixed_motor_program_penalty: f64,
    pub row_run_reward: f64,
    pub bottom_lock_reward: f64,
    pub row_jump_penalty: f64,
    pub redirect: f64,
    pub lateral_stretch: f64,
    pub adjacent_roll_long_gap_penalty: f64,
    pub index_stretch: f64,
    pub half_v_stretch: f64,
    pub digit_5_stretch: f64,
    pub digit_6_stretch: f64,
    pub cognitive_sweep_reward: f64,
    pub cognitive_known_walk_reward: f64,
    pub cognitive_compact_reward: f64,
    pub cognitive_vertical_reward: f64,
    pub cognitive_cap_per_step: f64,
    pub finger_axis_lateral: f64,
    pub finger_axis_opposite: f64,
    pub finger_axis_time: f64,
    // Per-finger calibration knobs. Defaults are hardcoded so the binary works
    // without a profile file. Config files only override selected fields.
    // Axis values are a lightweight 2D proxy for relaxed extension direction;
    // they are not medical-grade joint coordinates.
    pub left_pinky_axis_dx: f64,
    pub left_pinky_axis_dy: f64,
    pub left_ring_axis_dx: f64,
    pub left_ring_axis_dy: f64,
    pub left_middle_axis_dx: f64,
    pub left_middle_axis_dy: f64,
    pub left_index_axis_dx: f64,
    pub left_index_axis_dy: f64,
    pub right_index_axis_dx: f64,
    pub right_index_axis_dy: f64,
    pub right_middle_axis_dx: f64,
    pub right_middle_axis_dy: f64,
    pub right_ring_axis_dx: f64,
    pub right_ring_axis_dy: f64,
    pub right_pinky_axis_dx: f64,
    pub right_pinky_axis_dy: f64,
    pub left_index_lateral_factor: f64,
    pub right_index_lateral_factor: f64,
    pub left_middle_lateral_factor: f64,
    pub right_middle_lateral_factor: f64,
    pub left_ring_lateral_factor: f64,
    pub right_ring_lateral_factor: f64,
    pub left_pinky_lateral_factor: f64,
    pub right_pinky_lateral_factor: f64,
    pub left_index_repeat_factor: f64,
    pub right_index_repeat_factor: f64,
    pub left_middle_repeat_factor: f64,
    pub right_middle_repeat_factor: f64,
    pub left_ring_repeat_factor: f64,
    pub right_ring_repeat_factor: f64,
    pub left_pinky_repeat_factor: f64,
    pub right_pinky_repeat_factor: f64,
}

impl Default for Weights {
    fn default() -> Self {
        Self {
            base_key: 1.00,
            rest_distance: 0.40,
            dynamic_distance: 0.68,
            palm_distance: 0.22,
            palm_tension: 0.10,
            row_top: 0.09,
            row_home: -0.06,
            row_bottom: 0.22,
            row_number: 0.92,
            pinky_start: 0.26,
            shift: 1.10,
            left_shift_right_reach: 0.60,
            beat_interval: 1.00,
            finger_recovery: 2.72,
            movement_recovery: 0.16,
            movement_time_factor: 0.15,
            row_change_time: 0.055,
            stretch_time: 0.13,
            timing_wait: 1.55,
            same_key_motion: 0.42,
            same_finger_motion: 0.58,
            recent_same_finger: 0.16,
            two_finger_bounce: 0.42,
            abba_bounce: 0.70,
            same_hand: 0.025,
            hand_switch_onehand: 0.65,
            hand_switch_neutral: 0.08,
            hand_switch_alternation: -0.12,
            prefer_hand_penalty: 2.65,
            adjacent_roll_reward: -0.44,
            forward_roll_reward: -0.27,
            reverse_roll_penalty: 0.13,
            compact_cluster_reward: -0.18,
            smooth_trigram_reward: -0.50,
            reverse_trigram_penalty: 0.08,
            full_sweep_reward: -1.25,
            reverse_full_sweep_penalty: 0.42,
            upper_reverse_coupled_roll_reward: -0.36,
            upper_reverse_axis_relief: 0.95,
            upper_reverse_split_sweep_reward: -1.15,
            home_return_wait_relief: 0.92,
            pre_sweep_direction_change_penalty: 1.35,
            pre_sweep_direction_match_reward: -0.12,
            home_sweep_reward: -0.50,
            non_home_sweep_reward_factor: 0.55,
            mixed_row_sweep_penalty: 0.86,
            asymmetric_row_actuation: 0.46,
            motor_program_repeat_reward: -0.55,
            mixed_motor_program_penalty: 0.85,
            row_run_reward: -0.18,
            bottom_lock_reward: -0.17,
            row_jump_penalty: 0.34,
            redirect: 0.82,
            lateral_stretch: 0.70,
            adjacent_roll_long_gap_penalty: 0.72,
            index_stretch: 1.08,
            half_v_stretch: 0.34,
            digit_5_stretch: 0.65,
            digit_6_stretch: 1.40,
            cognitive_sweep_reward: -0.055,
            cognitive_known_walk_reward: -0.070,
            cognitive_compact_reward: -0.035,
            cognitive_vertical_reward: -0.035,
            cognitive_cap_per_step: 0.14,
            finger_axis_lateral: 0.82,
            finger_axis_opposite: 0.55,
            finger_axis_time: 0.055,
            left_pinky_axis_dx: -0.32,
            left_pinky_axis_dy: -1.00,
            left_ring_axis_dx: 0.26,
            left_ring_axis_dy: -1.00,
            left_middle_axis_dx: -0.25,
            left_middle_axis_dy: -1.00,
            left_index_axis_dx: -0.15,
            left_index_axis_dy: -1.00,
            right_index_axis_dx: 0.15,
            right_index_axis_dy: -1.00,
            right_middle_axis_dx: 0.25,
            right_middle_axis_dy: -1.00,
            right_ring_axis_dx: -0.26,
            right_ring_axis_dy: -1.00,
            right_pinky_axis_dx: 0.32,
            right_pinky_axis_dy: -1.00,
            left_index_lateral_factor: 0.82,
            right_index_lateral_factor: 0.82,
            left_middle_lateral_factor: 0.72,
            right_middle_lateral_factor: 0.72,
            left_ring_lateral_factor: 1.38,
            right_ring_lateral_factor: 1.38,
            left_pinky_lateral_factor: 1.55,
            right_pinky_lateral_factor: 1.55,
            left_index_repeat_factor: 0.92,
            right_index_repeat_factor: 0.92,
            left_middle_repeat_factor: 1.00,
            right_middle_repeat_factor: 1.00,
            left_ring_repeat_factor: 1.18,
            right_ring_repeat_factor: 1.18,
            left_pinky_repeat_factor: 1.38,
            right_pinky_repeat_factor: 1.38,
        }
    }
}
